apiVersion: v1
kind: Service
metadata:
  name: postgres-storage-service
spec:
  selector:
    app: postgres-db
  ports:
    - port: 5432
      targetPort: 5432
  # headless service, which means we can use the service name to identify the pods independently 
  # rather than relying on a single service name which load balances to random pod
  # headless service is good for stateful set
  clusterIP: None  