apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
spec:
  type: ClusterIP # default is clusterip and we can specify loadbalancer and nodeport
  selector:
    app: my-app
  ports:
    - port: 80        # service port
      targetPort: 80  # container port