apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: my-app
  template:
    metadata:
      name: my-ngx-pod
      labels:
        app: my-app
    spec:
      containers:
        - name: ngx-container
          image: nginx:latest
          ports:
            - containerPort: 80 
      