apiVersion: v1
kind: Service
metadata: 
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: my-node
  ports:
    - port: 80         # Service Port
      targetPort: 80   # container port
      nodePort: 30007  # Exposed Port (Optional, auto-assigned if omitted)